{
  "name": "This test will be broken",
  "status": "skipped",
  "statusDetails": {
    "message": "ValueError: Some error",
    "trace": "@allure.title(\"This test will be broken\")\n    @pytest.mark.xfail(reason='Так задумано')\n    def test_broken():\n>       raise ValueError(\"Some error\")\nE       ValueError: Some error\n\ntest_allure.py:21: ValueError"
  },
  "start": 1572434056477,
  "stop": 1572434056477,
  "uuid": "2693e1af-f306-43dc-bbcd-1d0fb3042902",
  "historyId": "985c3d972d231f87d0914b89f78754fd",
  "testCaseId": "cb41bd139e929d9eef92825c451cc27a",
  "fullName": "test_allure#test_broken",
  "labels": [
    {
      "name": "suite",
      "value": "test_allure"
    },
    {
      "name": "host",
      "value": "edg-xps"
    },
    {
      "name": "thread",
      "value": "14037-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "test_allure"
    }
  ]
}